// content.db -> the site's committed data.
//
// Writes src/data/{projects.json,domains.ts,roles.ts,project-roles.ts,site.ts} and
// copies every referenced media file into public/. Files are only rewritten when
// their contents actually change, so an unchanged publish produces no git noise.
//
// Nothing this module writes may carry a local filesystem path — the check at the
// bottom refuses to publish if one appears (see AGENTS.md).
import fs from 'node:fs';
import path from 'node:path';
import { REPO, MEDIA_DIR, db, listDomains, listProjects, listRoles, listEducation, allSettings, roleIdForProject, assetsFor } from './db.mjs';

const DATA = path.join(REPO, 'src', 'data');
const PUBLIC = path.join(REPO, 'public');
const PROJECTS_PUBLIC = path.join(PUBLIC, 'projects');
const MANIFEST = path.join(PROJECTS_PUBLIC, '.generated-media.json');

const pj = (v, fallback = []) => {
	try {
		return JSON.parse(v);
	} catch {
		return fallback;
	}
};

const written = new Map(); // path -> true (files this run wrote)
const stats = { files: 0, unchanged: 0, media: 0, projects: 0, skippedHidden: 0 };

function writeIfChanged(file, contents) {
	written.set(file, true);
	let current = null;
	try {
		current = fs.readFileSync(file, 'utf8');
	} catch {
		/* new file */
	}
	if (current === contents) {
		stats.unchanged++;
		return false;
	}
	fs.mkdirSync(path.dirname(file), { recursive: true });
	fs.writeFileSync(file, contents);
	stats.files++;
	return true;
}

/**
 * Resolve a stored media reference to a published URL, copying the file into
 * place. Accepts `media:<id>`, an absolute site path, or an external URL.
 */
function publishMedia(value, { slug = null, name = null } = {}) {
	if (!value) return '';
	if (typeof value !== 'string') return '';
	if (/^https?:/i.test(value)) return value;

	if (value.startsWith('media:')) {
		const id = Number(value.slice(6));
		const row = db.prepare('SELECT * FROM media WHERE id = ?').get(id);
		if (!row) return '';
		const dir = slug ? path.join(PROJECTS_PUBLIC, slug) : path.join(PUBLIC, 'media');
		const dest = path.join(dir, row.file);
		fs.mkdirSync(dir, { recursive: true });
		const source = path.join(MEDIA_DIR, row.file);
		if (!fs.existsSync(source)) return '';
		let same = false;
		try {
			same = fs.statSync(source).size === fs.statSync(dest).size;
		} catch {
			same = false;
		}
		if (!same) fs.copyFileSync(source, dest);
		stats.media++;
		const url = slug ? `/projects/${slug}/${row.file}` : `/media/${row.file}`;
		track(url);
		return url;
	}

	// already a site path — leave it alone
	return value;
}

// Track generated public files so a removed asset does not leave its file behind.
const generatedFiles = new Set();

function track(url) {
	if (url.startsWith('/projects/')) generatedFiles.add(url.replace(/^\//, ''));
	else if (url.startsWith('/media/')) generatedFiles.add(url.replace(/^\//, ''));
}

// ------------------------------------------------------------------ site ----
const settings = allSettings();
const landing = {
	site_title: settings.site_title || 'isidore.work',
	site_description: settings.site_description || '',
	email: settings.email || '',
	email2: settings.email2 || '',
	github_url: settings.github_url || '',
	linkedin_url: settings.linkedin_url || '',
	instagram_url: settings.instagram_url || '',
	landing_name: settings.landing_name || '',
	landing_selfie: settings.landing_selfie || '',
	landing_selfie_caption: settings.landing_selfie_caption || '',
	landing_availability: settings.landing_availability || '',
	landing_bio: settings.landing_bio || [],
	work_heading: settings.work_heading || 'Professional Work',
	work_blurb: settings.work_blurb || '',
	more_heading: settings.more_heading || '',
	more_blurb: settings.more_blurb || '',
	contact_heading: settings.contact_heading || '',
	contact_blurb: settings.contact_blurb || '',
};

const selfieUrl = publishMedia(landing.landing_selfie);
landing.landing_selfie = selfieUrl;

writeIfChanged(
	path.join(DATA, 'site.ts'),
	`// GENERATED by admin/generate.mjs from content.db — edit through the admin portal
// at /admin, not here. Re-running the generator overwrites this file.

export const SITE_TITLE = ${JSON.stringify(landing.site_title)};
export const SITE_DESCRIPTION = ${JSON.stringify(landing.site_description)};
export const EMAIL = ${JSON.stringify(landing.email)};
export const EMAIL2 = ${JSON.stringify(landing.email2)};
export const GITHUB_URL = ${JSON.stringify(landing.github_url)};
export const LINKEDIN_URL = ${JSON.stringify(landing.linkedin_url)};
export const INSTAGRAM_URL = ${JSON.stringify(landing.instagram_url)};

export interface Landing {
	name: string;
	selfie: string;
	selfieCaption: string;
	availability: string;
	bio: string[];
	workHeading: string;
	workBlurb: string;
	moreHeading: string;
	moreBlurb: string;
	contactHeading: string;
	contactBlurb: string;
}

export const LANDING: Landing = ${JSON.stringify(
		{
			name: landing.landing_name,
			selfie: landing.landing_selfie,
			selfieCaption: landing.landing_selfie_caption,
			availability: landing.landing_availability,
			bio: landing.landing_bio,
			workHeading: landing.work_heading,
			workBlurb: landing.work_blurb,
			moreHeading: landing.more_heading,
			moreBlurb: landing.more_blurb,
			contactHeading: landing.contact_heading,
			contactBlurb: landing.contact_blurb,
		},
		null,
		'\t',
	)};
`,
);

// --------------------------------------------------------------- domains ----
const domains = listDomains();
writeIfChanged(
	path.join(DATA, 'domains.ts'),
	`// GENERATED by admin/generate.mjs from content.db — the domain taxonomy and the
// accent colour each project card is keyed to. Edit through /admin.

export interface Domain {
	slug: string;
	label: string;
	blurb: string;
	color: string; // accent used for cards/chips
}

export const DOMAINS: Domain[] = [
${domains
	.map(
		(d) =>
			`\t{ slug: ${JSON.stringify(d.slug)}, label: ${JSON.stringify(d.label)}, blurb: ${JSON.stringify(
				d.blurb,
			)}, color: ${JSON.stringify(d.color)} },`,
	)
	.join('\n')}
];

export const CATEGORIES = ${JSON.stringify(settings.categories || ['School', 'Work', 'Personal'])} as const;

export const domainMap = Object.fromEntries(DOMAINS.map((d) => [d.slug, d]));
`,
);

// ----------------------------------------------------------------- roles ----
const roles = listRoles();
const roleLiteral = (r) => `\t{
\t\tid: ${JSON.stringify(r.id)},
\t\ttitle: ${JSON.stringify(r.title)},
\t\torg: ${JSON.stringify(r.org)},
\t\tlocation: ${JSON.stringify(r.location)},
\t\tkind: ${JSON.stringify(r.kind)},
\t\tstart: ${JSON.stringify(r.start)},
\t\tend: ${JSON.stringify(r.end)},
\t\tcurrent: ${r.current ? 'true' : 'false'},
\t\temployment: ${JSON.stringify(r.employment)},
\t\tsummary: ${JSON.stringify(r.summary)},
\t\tachievements: ${JSON.stringify(pj(r.achievements), null, '\t\t').replace(/\n/g, '\n\t\t')},
\t\tskills: ${JSON.stringify(pj(r.skills), null, '\t\t').replace(/\n/g, '\n\t\t')},
\t\ttools: ${JSON.stringify(pj(r.tools), null, '\t\t').replace(/\n/g, '\n\t\t')},
\t},`;

writeIfChanged(
	path.join(DATA, 'roles.ts'),
	`// GENERATED by admin/generate.mjs from content.db (the CV page's spine).

export interface Role {
	id: string;
	title: string;
	org: string;
	location: string;
	kind: "Role" | "Fellowship" | "Volunteer" | "Award" | "Credential";
	start: string;
	end: string; // empty when current or a single date
	current: boolean;
	employment: string;
	summary: string;
	achievements: string[];
	skills: string[];
	tools: string[];
}

export interface Education {
	institution: string;
	from: string;
	to: string;
	current: boolean;
}

export const ROLES: Role[] = [
${roles.map(roleLiteral).join('\n')}
];

export const POSITIONS: Role[] = ROLES.filter((r) => !["Award", "Credential"].includes(r.kind));
export const AWARDS: Role[] = ROLES.filter((r) => r.kind === "Award" || r.kind === "Credential");

export const EDUCATION: Education[] = [
${listEducation()
	.map(
		(e) => `\t{
\t\tinstitution: ${JSON.stringify(e.institution)},
\t\tfrom: ${JSON.stringify(e.from_text)},
\t\tto: ${JSON.stringify(e.to_text)},
\t\tcurrent: ${e.current ? 'true' : 'false'},
\t},`,
	)
	.join('\n')}
];
`,
);

// ------------------------------------------------------------- projects -----
const projects = listProjects();
const records = [];
for (const p of projects) {
	if (!p.visible) {
		stats.skippedHidden++;
		continue;
	}
	const assets = [];
	for (const a of assetsFor(p.id)) {
		const src = publishMedia(a.src, { slug: p.slug });
		if (!src) continue;
		const entry = { type: a.type || 'image', src };
		if (a.caption) entry.caption = a.caption;
		if (a.thumb) entry.thumb = publishMedia(a.thumb, { slug: p.slug });
		assets.push(entry);
	}
	const cover = p.cover ? publishMedia(p.cover, { slug: p.slug }) : '';

	const rec = {
		slug: p.slug,
		name: p.name,
		date: p.date,
		domain: p.domain_slug,
		category: p.category,
		audience: p.audience,
		effort: p.effort,
		timeHours: p.time_hours,
		summary: p.summary,
		hasVisuals: assets.length > 0 || Boolean(cover),
		tags: pj(p.tags),
		assets,
	};
	if (cover) rec.cover = cover;
	if (p.accent_color) rec.accentColor = p.accent_color;
	if (p.body) rec.body = p.body;
	if (p.course) rec.course = p.course;
	if (p.term) rec.term = p.term;
	if (p.org) rec.org = p.org;
	if (p.kind) rec.kind = p.kind;
	if (p.status) rec.status = p.status;
	const deliverables = pj(p.deliverables);
	const tools = pj(p.tools);
	if (deliverables.length) rec.deliverables = deliverables;
	if (tools.length) rec.tools = tools;
	if (p.redirect_from) rec.redirectFrom = p.redirect_from;
	records.push(rec);
}
// Newest first. Equal dates keep the database order (sort_order, preserved from the
// original file), and Array.prototype.sort is stable — so this is deterministic and
// re-running generate never reorders the file.
records.sort((a, b) => (a.date === b.date ? 0 : a.date < b.date ? 1 : -1));

writeIfChanged(path.join(DATA, 'projects.json'), `${JSON.stringify(records, null, '\t')}\n`);
stats.projects = records.length;

// ------------------------------------------------------- project -> role ----
const roleMap = {};
for (const p of projects) {
	const roleId = roleIdForProject(p.slug);
	if (roleId) roleMap[p.slug] = roleId;
}
// Sorted so the file does not depend on database row order — a re-import must
// produce byte-identical output.
const anchors = {};
for (const slug of Object.keys(roleMap).sort()) anchors[slug] = roleMap[slug];
writeIfChanged(
	path.join(DATA, 'project-roles.ts'),
	`// GENERATED by admin/generate.mjs — the CV role each Work-category project came
// out of. Edit through /admin (the project form's "CV role" field).

export const ROLE_BY_SLUG: Record<string, string> = ${JSON.stringify(anchors, null, '\t')};
`,
);

// --------------------------------------------------- stale media cleanup ----
// Only safe because the manifest lists exactly what a previous run produced. The
// guard below matters: a run against an empty or broken database would otherwise
// delete every published asset (including files tracked in git).
let previous = [];
try {
	previous = JSON.parse(fs.readFileSync(MANIFEST, 'utf8'));
} catch {
	previous = [];
}
let removed = 0;
if (generatedFiles.size === 0 && previous.length > 0) {
	console.warn(
		`generate: REFUSING stale-media cleanup — this run produced 0 published files but the ` +
			`manifest lists ${previous.length}. That means the content database is empty or the ` +
			`build is broken. Is the publish pipeline failing upstream?`,
	);
} else {
	for (const rel of previous) {
		if (generatedFiles.has(rel)) continue;
		const file = path.join(PUBLIC, rel);
		if (fs.existsSync(file)) {
			fs.unlinkSync(file);
			removed++;
		}
	}
	for (const rel of generatedFiles) {
		const dir = path.dirname(path.join(PUBLIC, rel));
		try {
			if (fs.existsSync(dir) && fs.readdirSync(dir).length === 0) fs.rmdirSync(dir);
		} catch {
			/* not empty / not ours */
		}
	}
	fs.mkdirSync(PROJECTS_PUBLIC, { recursive: true });
	fs.writeFileSync(MANIFEST, JSON.stringify([...generatedFiles].sort(), null, '	'));
}

// ------------------------------------------------------------ safety net ----
const suspects = [path.join(DATA, 'site.ts'), path.join(DATA, 'projects.json'), path.join(DATA, 'roles.ts')];
const LEAK = /(?:[A-Za-z]:\\\\|\/home\/izzy\/|\/Users\/|Google Drive|OneDrive)/;
for (const file of suspects) {
	const text = fs.readFileSync(file, 'utf8');
	if (LEAK.test(text)) {
		throw new Error(`refusing to publish: ${file} contains a local filesystem path`);
	}
}

console.log(
	`generate: ${stats.projects} projects (${stats.skippedHidden} hidden), ${stats.media} media files, ` +
		`${stats.files} written, ${stats.unchanged} unchanged, ${removed} stale removed`,
);
