// GENERATED by admin/generate.mjs from content.db — edit through the admin
// portal at /admin, not here. Re-running the generator overwrites this file.
//
// Kept in place so every existing `import { SITE_TITLE, EMAIL, ... } from '../consts'`
// keeps working; the values themselves now live in ./data/site.
export {
	SITE_TITLE,
	SITE_DESCRIPTION,
	EMAIL,
	EMAIL2,
	GITHUB_URL,
	LINKEDIN_URL,
	INSTAGRAM_URL,
	LANDING,
} from './data/site';
export type { Landing } from './data/site';
