// The homepage's "Professional Work" list: every project record whose category is
// `Work`, anchored to the CV role it came out of.
//
// The anchor is hand-maintained on purpose. `src/data/projects.json` is generated by
// `portfolio_db/export_site.py` and its `org` field is deliberately de-identified
// ("Internship employer", "U.S. Navy (HM-12)"), so the employer / role title / dates
// shown on the homepage come from `roles.ts` — the CV spine, generated from roles.csv.
// That keeps the generated files untouched and re-runnable.
//
// If a Work project gains no entry here it is reported (never silently dropped) and
// rendered without the role line, so a database rebuild shows up as a build warning.
import { projects, type Project } from '../lib/projects';
import { ROLES, type Role } from './roles';

const ROLE_BY_SLUG: Record<string, string> = {
	// American Energy Society — research intern (R01)
	'american-energy-society-energy-startups-dashboard': 'R01',
	'aes-research-data-documentation-and-onboarding': 'R01',
	'aes-flagship-energy-startups-report': 'R01',
	'aes-energy-startup-longitudinal-database': 'R01',
	// Dominion Energy — customer projects design intern (R04)
	'dominion-energy-summer-internship': 'R04',
	'dominion-route-planning-excel-tool': 'R04',
	'dominion-residential-power-hookup-project': 'R04',
	'dominion-municipal-and-utility-coordination': 'R04',
	// University of Virginia — undergraduate teaching assistant (R03)
	'uva-ta-applied-circuits-ece-2300': 'R03',
	// Fairlead Integrated Solutions (R06)
	'fairlead-electrical-assembly-technician': 'R06',
	// U.S. Navy, HM-12 (R05)
	'navy-maintenance-training-program': 'R05',
	'navy-mh53e-airframe-maintenance': 'R05',
	// Riverside Kayak Connection (R07)
	'rkc-detroit-historical-canal-tour-and-tour-guide-manual': 'R07',
	'rkc-coaching-records-and-fun-start-lesson-plans': 'R07',
	'rkc-coaching-and-canal-tour': 'R07',
};

export interface ProfessionalEntry {
	project: Project;
	role?: Role;
}

const work = projects.filter((p) => p.category === 'Work');

const unanchored = work.filter((p) => !ROLE_BY_SLUG[p.slug]).map((p) => p.slug);
if (unanchored.length) {
	console.warn(
		`[professional] Work project(s) with no role anchor in ROLE_BY_SLUG — ` +
			`add them so the homepage shows employer and dates: ${unanchored.join(', ')}`,
	);
}

/** Work-category records, newest first (projects.json is already date-sorted). */
export const professionalEntries: ProfessionalEntry[] = work.map((project) => ({
	project,
	role: ROLES.find((r) => r.id === ROLE_BY_SLUG[project.slug]),
}));

/** Everything that is not professional work — linked, not listed, on the homepage. */
export const otherProjectCount = projects.length - work.length;
