// GENERATED by admin/generate.mjs from content.db (the CV page's spine).

export interface Role {
	id: string;
	title: string;
	org: string;
	location: string;
	kind: "Role" | "Fellowship" | "Volunteer" | "Award" | "Credential";
	start: string;
	end: string; // empty when current or a single date
	current: boolean;
	employment: string;
	summary: string;
	achievements: string[];
	skills: string[];
	tools: string[];
}

export interface Education {
	institution: string;
	from: string;
	to: string;
	current: boolean;
}

export const ROLES: Role[] = [
	{
		id: "R01",
		title: "Research Intern",
		org: "American Energy Society",
		location: "San Francisco, CA (remote)",
		kind: "Role",
		start: "2026-05",
		end: "present",
		current: true,
		employment: "Internship (part-time)",
		summary: "Research intern on the energy-tech startup tracking programme.",
		achievements: [
				"Sourced >1,300 energy-tech startups from accelerators and pitch competitions into a longitudinal database",
				"analysed and visualised the data in Excel/Python for the flagship startups report",
				"wrote the data-collection, cleaning and analysis documentation used to train incoming interns."
		],
		skills: [
				"data-sourcing",
				"dataset-curation",
				"analysis",
				"visualisation",
				"documentation",
				"python",
				"excel"
		],
		tools: [
				"Excel",
				"Python",
				"D3",
				"Google Sheets"
		],
	},
	{
		id: "R02",
		title: "Undergraduate Research Assistant (Gupta Lab)",
		org: "University of Virginia",
		location: "Charlottesville, VA",
		kind: "Role",
		start: "2026-01",
		end: "2026-06",
		current: false,
		employment: "Part-time",
		summary: "Lab research on selective material recovery from hard disk drive components.",
		achievements: [
				"Conducted laser-ablation experiments on HDD components for selective material recovery",
				"evaluated scalable recycling methods to improve critical-material lifecycles and reduce electronic waste."
		],
		skills: [
				"libs",
				"eds",
				"laser-ablation",
				"materials-characterisation",
				"spectroscopy",
				"experimental-design"
		],
		tools: [
				"LIBS",
				"EDS",
				"laser ablation rig",
				"Python"
		],
	},
	{
		id: "R03",
		title: "Undergraduate Teaching Assistant, Applied Circuits (ECE 2300)",
		org: "University of Virginia",
		location: "Charlottesville, VA",
		kind: "Role",
		start: "2025-08",
		end: "2025-12",
		current: false,
		employment: "Part-time",
		summary: "Supported the ECE 2300 applied-circuits labs and student success.",
		achievements: [
				"Ran lab sections and supported students through circuit analysis, instrumentation and troubleshooting",
				"graded work and produced worked solutions."
		],
		skills: [
				"lab-instruction",
				"circuit-analysis",
				"grading",
				"mentoring"
		],
		tools: [
				"Multisim",
				"AD2"
		],
	},
	{
		id: "R04",
		title: "Customer Projects Designer I, Intern",
		org: "Dominion Energy",
		location: "Norfolk, VA",
		kind: "Role",
		start: "2025-05",
		end: "2025-08",
		current: false,
		employment: "Internship (full-time)",
		summary: "Summer design internship in electric distribution customer projects.",
		achievements: [
				"Completed all phases of a residential power hookup (site visits, calculations, permitting, construction sketches)",
				"coordinated with Chesapeake/Norfolk city offices and the Elizabeth River Project on permitting, telecom joint-use and site readiness",
				"built an Excel route-planning tool that bypasses Google Maps limits, demoed it to the team and wrote the adoption job aid."
		],
		skills: [
				"distribution-design",
				"load-calculation",
				"permitting",
				"stakeholder-liaison",
				"excel-tooling",
				"process-improvement"
		],
		tools: [
				"AutoCAD",
				"Excel"
		],
	},
	{
		id: "R05",
		title: "Helicopter Airframe Mechanic, Active Duty (E-5)",
		org: "U.S. Navy (HM-12, MH-53E Sea Dragon)",
		location: "Norfolk, VA",
		kind: "Role",
		start: "2019-04",
		end: "2024-01",
		current: false,
		employment: "Full-time (military)",
		summary: "Four years maintaining flight-critical airframe systems on the Navy's heavy-lift helicopter.",
		achievements: [
				"Inspected and repaired landing gear, hydraulics and flight controls to Naval Aviation standards",
				"led maintenance crews through time-critical discrepancy resolution",
				"interpreted technical manuals and engineering directives to determine repair feasibility",
				"managed training for 56 personnel and raised programme compliance from 91% to 97% over ten months."
		],
		skills: [
				"hydraulics",
				"flight-controls",
				"airframe-systems",
				"technical-manuals",
				"compliance",
				"leadership",
				"training-management"
		],
		tools: [
				"Naval Aviation maintenance directives"
		],
	},
	{
		id: "R06",
		title: "1st Class Electrical Assembly Technician (DoD Skillbridge)",
		org: "Fairlead Integrated Solutions",
		location: "Portsmouth, VA",
		kind: "Role",
		start: "2023-03",
		end: "2024-02",
		current: false,
		employment: "Skillbridge (full-time)",
		summary: "Skillbridge placement assembling and troubleshooting naval electronic assemblies.",
		achievements: [
				"Electrical assembly to mil-spec workmanship standards",
				"EMI-filter troubleshooting documented in a recorded Q&A session."
		],
		skills: [
				"electrical-assembly",
				"emi-filtering",
				"harnessing",
				"mil-spec-workmanship"
		],
		tools: [
				"hand tools",
				"test equipment"
		],
	},
	{
		id: "R07",
		title: "Youth Coach and Historical Canal Tour Guide",
		org: "Riverside Kayak Connection (RKC)",
		location: "Detroit, MI",
		kind: "Role",
		start: "2017-06",
		end: "2019-06",
		current: false,
		employment: "Seasonal",
		summary: "Summer coaching and public-history guiding on the Detroit River canals.",
		achievements: [
				"Coached youth paddling programmes and led public historical canal tours",
				"authored the RKC tour guide manual and kept coaching/experience records."
		],
		skills: [
				"coaching",
				"public-speaking",
				"curriculum-writing",
				"local-history"
		],
		tools: [
				"Google Docs"
		],
	},
	{
		id: "R08",
		title: "Civic Cornerstone Fellowship - cohort member",
		org: "University of Virginia",
		location: "Charlottesville, VA",
		kind: "Fellowship",
		start: "2025-09",
		end: "present",
		current: true,
		employment: "Extracurricular",
		summary: "Member of a UVA civic-dialogue cohort.",
		achievements: [
				"Participates in structured civic dialogue across political difference."
		],
		skills: [
				"civic-dialogue",
				"facilitation"
		],
		tools: [],
	},
	{
		id: "R09",
		title: "Fix-It DC Coach",
		org: "Fix-It DC",
		location: "Washington, DC",
		kind: "Volunteer",
		start: "2026-06",
		end: "2026-07",
		current: false,
		employment: "Volunteer",
		summary: "Volunteer repair coach at free community repair events.",
		achievements: [
				"Repaired electronics and home appliances while coaching owners through the diagnosis."
		],
		skills: [
				"electronics-repair",
				"diagnostics",
				"appliance-systems",
				"teaching"
		],
		tools: [
				"multimeter",
				"soldering"
		],
	},
	{
		id: "A01",
		title: "Student Veteran Service Award Scholarship",
		org: "Dominion Energy",
		location: "",
		kind: "Award",
		start: "2025-08",
		end: "",
		current: false,
		employment: "",
		summary: "Dominion Energy scholarship recognising student-veteran service.",
		achievements: [],
		skills: [],
		tools: [],
	},
	{
		id: "A02",
		title: "Blue Jacket of the Year",
		org: "U.S. Navy, HM-12",
		location: "Norfolk, VA",
		kind: "Award",
		start: "2023-12",
		end: "",
		current: false,
		employment: "",
		summary: "Squadron-level recognition for sustained superior performance.",
		achievements: [],
		skills: [],
		tools: [],
	},
	{
		id: "C01",
		title: "Fundamentals of Engineering (FE) Exam - Electrical and Computer Engineering",
		org: "NCEES",
		location: "",
		kind: "Credential",
		start: "2026-06",
		end: "",
		current: false,
		employment: "",
		summary: "Passed the FE Electrical and Computer Engineering exam.",
		achievements: [],
		skills: [
				"engineering-fundamentals"
		],
		tools: [],
	},
];

export const POSITIONS: Role[] = ROLES.filter((r) => !["Award", "Credential"].includes(r.kind));
export const AWARDS: Role[] = ROLES.filter((r) => r.kind === "Award" || r.kind === "Credential");

export const EDUCATION: Education[] = [
	{
		institution: "University of Virginia",
		from: "Fall 2024",
		to: "Fall 2026",
		current: true,
	},
	{
		institution: "Germanna Community College",
		from: "Spring 2024",
		to: "Spring 2024",
		current: false,
	},
	{
		institution: "Tidewater Community College",
		from: "Summer 2021",
		to: "Fall 2023",
		current: false,
	},
	{
		institution: "Wayne State University",
		from: "Winter 2017",
		to: "Winter 2019",
		current: false,
	},
];
