// GENERATED by admin/generate.mjs from content.db — edit through the admin portal
// at /admin, not here. Re-running the generator overwrites this file.

export const SITE_TITLE = "isidore.work";
export const SITE_DESCRIPTION = "Projects across power & energy, embedded hardware, software & data, research, and policy.";
export const EMAIL = "isidore@virginia.edu";
export const EMAIL2 = "isidore2048@gmail.com";
export const GITHUB_URL = "https://github.com/harris11ax";
export const LINKEDIN_URL = "https://www.linkedin.com/in/isidore-larocco/";
export const INSTAGRAM_URL = "";

export interface Landing {
	name: string;
	selfie: string;
	selfieCaption: string;
	bio: string[];
	workHeading: string;
	workBlurb: string;
	moreHeading: string;
	moreBlurb: string;
	contactHeading: string;
	contactBlurb: string;
}

export const LANDING: Landing = {
	"name": "Isidore LaRocco",
	"selfie": "/blog-placeholder-about.jpg",
	"selfieCaption": "Placeholder — selfie to come.",
	"bio": [
		"Electrical &amp; computer engineering student at the University of Virginia, after four years as an MH-53E Sea Dragon airframe mechanic in the U.S. Navy. Work across power &amp; energy systems, embedded hardware, software &amp; data, lab research and science-and-technology policy.",
		"Most recently a research intern at the American Energy Society, tracking energy-tech startups; before that a summer design internship at Dominion Energy and a DoD Skillbridge electrical-assembly placement at Fairlead Integrated Solutions."
	],
	"workHeading": "Professional Work",
	"workBlurb": "Roles held for an employer or institution — {count} records, newest first. Each entry links to its full write-up with the documents and images that came out of it.",
	"moreHeading": "Everything else",
	"moreBlurb": "Coursework, personal builds, research and volunteer programmes — {count} more records, filterable by domain and category. Roles, awards and credentials are on the <a href=\"/cv\">CV page</a>.",
	"contactHeading": "Get in touch",
	"contactBlurb": "Email is the fastest way to reach me; LinkedIn works too. The <a href=\"/contact\">contact page</a> lists both addresses."
};
